language: julia

os:
  - linux
  - osx
  
julia:
  - 1.0
  - 1.3
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly
    - julia: 1.0

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
